name: internet_file
description: A internet file getter (also optional downloader) that works in all platforms
repository: https://github.com/rbcprolabs/packages.dart/tree/master/packages/internet_file
issue_tracker: https://github.com/rbcprolabs/packages.dart/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+internet_file%22
version: 1.0.0+2

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  http: ^0.13.4
  path: ^1.8.0
  universal_file: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
